kind: Pod
apiVersion: v1
metadata:
  name: uploader
  labels: 
    app: uploader
spec:
  containers:
    - name: uploader-service
      image: lazydev400/file-uploader
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  nodeSelector:
    placement: worker